### ISSUE TITLE
Storage as real storage

### ISSUE THREAD

**Issue by beckmx** [maximkulkin/esp-homekit#101]
Hello, I would like to add some values, do you think I can use the storage methods in the storage.h, from what I saw, I can create a "fake" accesory and populate it with something, right? or should I need to use another library?

Greetings!

**Comment by maximkulkin** [comment]
First, it is much easier to use a library instead of trying to use weird tools to achieve same. Also, if you just want to store a couple of values, you can use [sysparam API](https://github.com/SuperHouse/esp-open-rtos/blob/master/core/sysparam.c) for that. Here is me using sysparams to store wifi-config settings: https://github.com/maximkulkin/esp-wifi-config/blob/master/src/wifi_config.c#L780-L795
