### ISSUE TITLE
Homekit Speaker

### ISSUE THREAD

**Issue by AustinRobinson** [maximkulkin/esp-homekit#62]
Are there any examples or can someone provide an example on how to get a speaker working with this library?

**Comment by renssies** [comment]
Making a speaker with this library in impossible. A HomeKit speaker is a speaker with WiFi and AirPlay 2. And sadly AirPlay 2 is limited to MFi licensees who have a strict NDA.

However people could reverse engineer airplay 2 (like the did with airplay 1) but unfortunately that hasn’t happened yet

**Comment by AustinRobinson** [comment]
Is there any documentation on how they reverse engineered airplay 1?

**Comment by AdySan** [comment]
See this https://github.com/mikebrady/shairport-sync/issues/535

**Comment by timoschilling** [comment]
HomeKit Speaker is not the same as an AirPlay Speaker.

It is right what @renssies says About the AirPlay 2 Speeker.

But it is possible to build an HomeKit Speaker with this lib.

Take a look Accessory Identifier and the related Service and add them to this projekt.

Here are the related files from an Go based lib:
https://github.com/brutella/hc/blob/master/service/speaker.go
https://github.com/brutella/hc/blob/master/characteristic/mute.go
https://github.com/brutella/hc/blob/master/characteristic/volume.go

**Comment by renssies** [comment]
@timoschilling: those are the speaker services that can only used for cameras and video doorbells sadly

**Comment by timoschilling** [comment]
That's not true!

Here is an Devise Created by the original Apple HomeKit Accessory Simulator:
![image](https://user-images.githubusercontent.com/165599/46974920-9a42bd80-d0c5-11e8-9599-d20676ce149d.png)
![image](https://user-images.githubusercontent.com/165599/46974940-a75fac80-d0c5-11e8-8ad1-db3103ac5642.png)

**Comment by renssies** [comment]
Yeah, that is speaker control, it is made for controlling the speaker of cameras and video doorbells. It's not supported by the official Home app but you can use it to build your own accessories to control a speaker using a different HomeKit (like the Home app by Matthias that @timoschilling is using)

However it won't let you play music to it. That is only for AirPlay 2.

**Comment by timoschilling** [comment]
Sure, thats HomeKit works! But your statement `Making a speaker with this library in impossible.` isn't right, it's possible. HomeKit this for controlling things not for streaming Media.

**Comment by timoschilling** [comment]
It's like building an doorbell or an webcam with HomeKit, the controlling is the domain of HomeKit the Streaming technology not.

**Comment by AustinRobinson** [comment]
So to be able to stream music, Airplay 2 would need to be reverse engineered?

**Comment by renssies** [comment]
That is true, however, most people that mean a "HomeKit speaker" mean a speaker that appears in the Home app, which is an AirPlay 2 speaker. 

So yes, you can build a HomeKit speaker with this library, meaning a speaker that you can control with a third party home app. However, you can't build a speaker that you can control using the Home app or stream music to. 

And yes, in order to make a speaker that appears in the Home app and that you can stream music too from throughout iOS it will need to be an AirPlay 2 speaker. And in order to make one as a maker/hobbyist, you will have to wait for AirPlay 2 to be reverse engineered :)

**Comment by AustinRobinson** [comment]
Ok thanks

**Comment by timoschilling** [comment]
There is one other DIY way, buy an Apple AirPort Express A1392 wich has an 3.5 mm audiojack and build it in your speaker. The A1392 has become AirPlay 2 support via an software update.

**Comment by mentaluproar** [comment]
Will this do what you want?
https://github.com/mikebrady/shairport-sync

**Comment by maximkulkin** [comment]
@mentaluproar I am sure that there are numerous programs that implement that. The idea here was to put everything onto a $5 hardware.

**Comment by Neustradamus** [comment]
Any news?

**Comment by mentaluproar** [comment]
> Any news?

Airplay2 was recently reverse engineered. I’d expect renewed interest in this soon.

**Comment by maximkulkin** [comment]
I would say, interest would renew if there would be off the shelf kits with ESP32 and speaker.

**Comment by maximkulkin** [comment]
Closing this for now, not gonna happen in near future

**Comment by maximkulkin** [comment]
Because do not plan to do that

**Comment by Neustradamus** [comment]
It is not good to close this ticket if not solved... One guy can develop it...

**Comment by maximkulkin** [comment]
1. Didn't happen so far. Frankly, nobody here ever worked on an issue (he did not report himself), so this is list is mostly for me and I do not want it hanging there.
2. This issue is not related to HomeKit in general, AirPlay has nothing to do with HomeKit. Issue list is not a collection of random notes and memes from internets, it's a list of what needs to be done for this particular repo.
